import Link from "next/link";
import type { Metadata } from "next";
import { MessageSquare } from "lucide-react";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { listQuestionBankEntries } from "@/lib/interviewSeo";

export const metadata: Metadata = {
  title: "Real Interview Questions by Company | Sortie",
  description:
    "Browse real interview questions grounded in each company's actual role and context — generated by Sortie's Interview Prep engine, not generic lists.",
};

export const revalidate = 3600;

// Programmatic SEO hub (build-plan.md's Phase 19 homepage research) —
// crawlable index linking to every individual company/role page below,
// built from real interview_question_banks rows only (lib/interviewSeo.ts
// excludes known test data, never fabricates an entry).
export default async function InterviewQuestionsHubPage() {
  const entries = await listQuestionBankEntries();

  return (
    <>
      <Navbar />
      <main className="mx-auto flex max-w-4xl flex-col gap-10 px-4 py-16 sm:px-6 lg:px-8">
        <div className="flex flex-col gap-4">
          <p className="inline-flex w-fit items-center gap-1.5 rounded-full bg-agent-light px-3 py-1 font-mono text-[11px] font-semibold uppercase tracking-wide text-agent-dark">
            <MessageSquare className="h-3.5 w-3.5" />
            Interview Prep
          </p>
          <h1 className="font-display text-3xl font-bold tracking-tight text-text-primary sm:text-4xl">
            Real interview questions, by company and role
          </h1>
          <p className="text-lg leading-8 text-text-secondary">
            Every question below is grounded in a real company&apos;s actual role and context — not a generic
            list. Sortie&apos;s Interview Prep engine builds these for real candidates preparing for a real
            interview.
          </p>
        </div>

        {entries.length === 0 ? (
          <p className="text-sm text-text-secondary">No question banks published yet — check back soon.</p>
        ) : (
          <ul className="grid gap-3 sm:grid-cols-2">
            {entries.map((entry) => (
              <li key={entry.slug}>
                <Link
                  href={`/interview-questions/${entry.slug}`}
                  className="block rounded-xl border border-border bg-surface p-4 transition-colors hover:bg-surface-secondary"
                >
                  <p className="font-medium text-text-primary">{entry.roleFamily}</p>
                  <p className="mt-1 text-sm text-text-secondary">
                    at {entry.company}
                    {entry.seniority ? ` · ${entry.seniority}` : ""}
                  </p>
                  <p className="mt-2 text-xs text-text-muted">{entry.questions.length} real questions</p>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </main>
      <Footer />
    </>
  );
}
