"use server";

import { requireUser } from "@/lib/auth";
import { createInsforgeServer } from "@/lib/insforge-server";
import { checkRateLimit } from "@/lib/rateLimit";
import { checkAndConsumeUsage } from "@/lib/usage";
import { toUserMessage } from "@/lib/errors";
import {
  buildCacheKey,
  generateQuestionBank,
  generateQuestionDetails,
  generatePracticeKit,
  normalizeRoleFamily,
  type InterviewQuestion,
  type PracticeKit,
  type QuestionBank,
  type QuestionDetails,
} from "@/lib/interviewQuestions";

type QuestionBankRow = {
  id: string;
  company: string;
  role_family: string;
  seniority: string;
  questions: InterviewQuestion[];
  generated_at: string;
};

function toQuestionBank(row: QuestionBankRow): QuestionBank {
  return {
    id: row.id,
    company: row.company,
    roleFamily: row.role_family,
    seniority: row.seniority,
    questions: row.questions,
    generatedAt: row.generated_at,
  };
}

type Result = { success: true; bank: QuestionBank } | { success: false; error: string };

// Cache-check-then-generate: a hit is a free read (no rate limit, no usage
// consumed, no AI call) — only a genuine miss triggers real generation and
// gets gated. Shared across every user (interview_question_banks has no
// user_id column, see the migration), so most calls after the first for any
// given (company, role_family, seniority) are instant free reads.
export async function getOrGenerateQuestionBank(
  rawCompany: string,
  rawTitle: string,
  rawSeniority: string,
): Promise<Result> {
  const user = await requireUser();
  const company = rawCompany.trim();
  const roleFamily = normalizeRoleFamily(rawTitle);
  const seniority = rawSeniority.trim();

  if (!company || !roleFamily) {
    return { success: false, error: "Enter at least a company and a role." };
  }

  const cacheKey = buildCacheKey(company, roleFamily, seniority);

  try {
    const insforge = await createInsforgeServer();

    const { data: existing } = await insforge.database
      .from("interview_question_banks")
      .select("id,company,role_family,seniority,questions,generated_at")
      .eq("cache_key", cacheKey)
      .maybeSingle<QuestionBankRow>();

    if (existing) {
      return { success: true, bank: toQuestionBank(existing) };
    }

    const rateLimit = await checkRateLimit(insforge, user.id, user.email, "interview/question-bank");
    if (!rateLimit.allowed) {
      return { success: false, error: rateLimit.error };
    }

    const usage = await checkAndConsumeUsage(insforge, user.id, user.email, "interview_question_bank");
    if (!usage.allowed) {
      return { success: false, error: usage.error };
    }

    const questions = await generateQuestionBank(company, roleFamily, seniority);

    const { data: inserted, error } = await insforge.database
      .from("interview_question_banks")
      .insert([
        {
          cache_key: cacheKey,
          company,
          role_family: roleFamily,
          seniority: seniority || "unspecified",
          questions,
        },
      ])
      .select("id,company,role_family,seniority,questions,generated_at")
      .single<QuestionBankRow>();

    // A concurrent request for the same cache key can lose the unique-
    // constraint race — fall back to reading whatever the winner inserted
    // rather than surfacing a spurious error for a real cache hit.
    if (error || !inserted) {
      const { data: raceWinner } = await insforge.database
        .from("interview_question_banks")
        .select("id,company,role_family,seniority,questions,generated_at")
        .eq("cache_key", cacheKey)
        .maybeSingle<QuestionBankRow>();

      if (raceWinner) return { success: true, bank: toQuestionBank(raceWinner) };

      console.error("[actions/interviewQuestions] insert failed", error);
      return { success: false, error: "Couldn't save the generated question bank. Please try again." };
    }

    return { success: true, bank: toQuestionBank(inserted) };
  } catch (error) {
    console.error("[actions/interviewQuestions] getOrGenerateQuestionBank", error);
    return { success: false, error: toUserMessage(error, "Failed to load interview questions.") };
  }
}

type DetailsResult = { success: true; details: QuestionDetails } | { success: false; error: string };

// Lazy per-question deep content — addressed by array index, not a stable
// id (see lib/interviewQuestions.ts's InterviewQuestion.details comment).
// A genuine cache hit (details already generated by an earlier user on this
// shared bank row) is a free read, same shape as getOrGenerateQuestionBank
// above.
export async function getQuestionDetails(bankId: string, questionIndex: number): Promise<DetailsResult> {
  const user = await requireUser();

  try {
    const insforge = await createInsforgeServer();

    const { data: bank } = await insforge.database
      .from("interview_question_banks")
      .select("id,company,role_family,seniority,questions")
      .eq("id", bankId)
      .maybeSingle<QuestionBankRow>();

    if (!bank) {
      return { success: false, error: "Question bank not found" };
    }

    const question = bank.questions[questionIndex];
    if (!question) {
      return { success: false, error: "Question not found" };
    }

    if (question.details) {
      return { success: true, details: question.details };
    }

    const usage = await checkAndConsumeUsage(insforge, user.id, user.email, "question_detail_generation");
    if (!usage.allowed) {
      return { success: false, error: usage.error };
    }

    const details = await generateQuestionDetails(question, bank.company, bank.role_family, bank.seniority);

    // Re-fetch immediately before writing back — this table is shared
    // across every user (no user_id column), so a concurrent request for a
    // DIFFERENT question on the same bank row could otherwise be clobbered
    // by a stale full-array replace. Same read-then-write race-window
    // tolerance as lib/usage.ts, just narrowed as much as practical here.
    const { data: fresh } = await insforge.database
      .from("interview_question_banks")
      .select("questions")
      .eq("id", bankId)
      .maybeSingle<{ questions: InterviewQuestion[] }>();

    const questions = fresh?.questions ?? bank.questions;
    if (questions[questionIndex]) {
      questions[questionIndex] = { ...questions[questionIndex], details };
    }

    const { error: updateError } = await insforge.database
      .from("interview_question_banks")
      .update({ questions })
      .eq("id", bankId);

    if (updateError) {
      // Still return the generated details even if the cache write failed —
      // the user already paid the usage cost for this generation, don't
      // make them re-pay for a save-only failure.
      console.error("[actions/interviewQuestions] getQuestionDetails persist", updateError);
    }

    return { success: true, details };
  } catch (error) {
    console.error("[actions/interviewQuestions] getQuestionDetails", error);
    return { success: false, error: toUserMessage(error, "Failed to load question details.") };
  }
}

type PracticeKitResult = { success: true; practiceKit: PracticeKit } | { success: false; error: string };

// Practice Sandbox (build-plan.md §N/§P) — exact same lazy-generate-and-
// persist shape as getQuestionDetails above, just a separate field
// (practiceKit) and a separate usage action, since it's a distinct artifact
// generated on a distinct trigger (opening the sandbox, not expanding the
// study card).
export async function getPracticeKit(bankId: string, questionIndex: number): Promise<PracticeKitResult> {
  const user = await requireUser();

  try {
    const insforge = await createInsforgeServer();

    const { data: bank } = await insforge.database
      .from("interview_question_banks")
      .select("id,company,role_family,seniority,questions")
      .eq("id", bankId)
      .maybeSingle<QuestionBankRow>();

    if (!bank) {
      return { success: false, error: "Question bank not found" };
    }

    const question = bank.questions[questionIndex];
    if (!question) {
      return { success: false, error: "Question not found" };
    }

    if (question.practiceKit) {
      return { success: true, practiceKit: question.practiceKit };
    }

    const usage = await checkAndConsumeUsage(insforge, user.id, user.email, "practice_kit_generation");
    if (!usage.allowed) {
      return { success: false, error: usage.error };
    }

    const practiceKit = await generatePracticeKit(question, bank.company, bank.role_family);

    // Same read-then-write race-window tolerance as getQuestionDetails above
    // — this table is shared across every user, no user_id column.
    const { data: fresh } = await insforge.database
      .from("interview_question_banks")
      .select("questions")
      .eq("id", bankId)
      .maybeSingle<{ questions: InterviewQuestion[] }>();

    const questions = fresh?.questions ?? bank.questions;
    if (questions[questionIndex]) {
      questions[questionIndex] = { ...questions[questionIndex], practiceKit };
    }

    const { error: updateError } = await insforge.database
      .from("interview_question_banks")
      .update({ questions })
      .eq("id", bankId);

    if (updateError) {
      console.error("[actions/interviewQuestions] getPracticeKit persist", updateError);
    }

    return { success: true, practiceKit };
  } catch (error) {
    console.error("[actions/interviewQuestions] getPracticeKit", error);
    return { success: false, error: toUserMessage(error, "Failed to build the practice exercise.") };
  }
}
